#ifndef MODE_TASK_H
#define MODE_TASK_H

typedef enum
{
	MODE_STATE_STARTUP			= 0x00,
	MODE_STATE_STARTUP_WAIT		= 0x01,
	MODE_STATE_EXIT_SETTINGS	= 0x02,
	MODE_STATE_OPERATE_MSG		= 0x03,
	MODE_STATE_OPERATE_MAIN_WAIT = 0x04,
	MODE_STATE_OPERATE_MAIN		= 0x05,
	MODE_STATE_MACRO_STORE1		= 0x06,	
	MODE_STATE_MACRO_STORE2		= 0x07,	
	MODE_STATE_MACRO_STORE3		= 0x08,	
	MODE_STATE_WPM_MSG			= 0x09,
	MODE_STATE_WPM_MAIN_WAIT	= 0x0A,
	MODE_STATE_WPM_MAIN			= 0x0B,
	MODE_STATE_TONE_MSG			= 0x0C,
	MODE_STATE_TONE_MAIN_WAIT	= 0x0D,
	MODE_STATE_TONE_MAIN		= 0x0E,
	MODE_STATE_KEY_MSG			= 0x0F,
	MODE_STATE_KEY_VAL_MSG		= 0x10,
	MODE_STATE_KEY_MAIN_WAIT	= 0x11,
	MODE_STATE_KEY_MAIN			= 0x12,
	MODE_STATE_OUT_MSG			= 0x13,
	MODE_STATE_OUT_VAL_MSG		= 0x14,
	MODE_STATE_OUT_MAIN_WAIT	= 0x15,
	MODE_STATE_OUT_MAIN			= 0x16,
	MODE_STATE_SPKR_MSG			= 0x17,
	MODE_STATE_SPKR_MAIN_WAIT	= 0x18,
	MODE_STATE_SPKR_MAIN		= 0x19,
	MODE_STATE_EAR_MSG			= 0x1A,
	MODE_STATE_EAR_MAIN_WAIT	= 0x1B,
	MODE_STATE_EAR_MAIN			= 0x1C,
	
	MODE_POWERDOWN	= 0xFE,
	
} OP_STATE_ENUM ;

void ModeTask();
	
#endif
